name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build build_ch6
      run: cargo build --verbose
      working-directory: ./ch6_assembler
    - name: Build build_ch7_8
      run: cargo build --verbose
      working-directory: ./ch7_ch8_vm_translator
    - name: Run test_ch7_8
      run: cargo test --verbose --package parser --lib parser::tests
      working-directory: ./ch7_ch8_vm_translator
